# Generated by Django 5.2.7 on 2025-10-22 07:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kursy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pytania',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tresc', models.TextField()),
                ('typ', models.CharField(max_length=50)),
                ('punkty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uprawnienia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('haslo', models.CharField(max_length=255)),
                ('status_uzytkownika', models.CharField(max_length=20)),
                ('data_rejestracji', models.DateTimeField(auto_now_add=True)),
                ('potwierdzony_email', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Odpowiedzi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tresc', models.TextField()),
                ('poprawna', models.BooleanField(default=False)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odpowiedzi', to='portal.pytania')),
            ],
        ),
        migrations.CreateModel(
            name='Testy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=200)),
                ('prog_zdawalnosci', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testy', to='portal.kursy')),
            ],
        ),
        migrations.AddField(
            model_name='pytania',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pytania', to='portal.testy'),
        ),
        migrations.CreateModel(
            name='UprawnieniaUzytkownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uprawnienia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uprawnienia', to='portal.uprawnienia')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uprawnienia_uzytkownika', to='portal.uzytkownicy')),
            ],
        ),
        migrations.CreateModel(
            name='OcenyKursow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gwiazdki', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('komentarz', models.TextField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny_kursow', to='portal.kursy')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny_kursow', to='portal.uzytkownicy')),
            ],
        ),
        migrations.AddField(
            model_name='kursy',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kursy', to='portal.uzytkownicy'),
        ),
        migrations.CreateModel(
            name='Kursanci',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postep', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kursanci', to='portal.kursy')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kursanci', to='portal.uzytkownicy')),
            ],
        ),
    ]
